/**
 * User-facing copy for the dashboard shell and its cards.
 * Ledger form chrome lives in `ledger-copy.ts`.
 */
export const dashboardCopy = {
    headTitle: 'Dashboard',
    comingSoon: 'Coming soon',
    goToSlide: (n: number) => `Go to slide ${n}`,

    header: {
        openSettings: 'Open settings',
        reportProblem: 'Report a problem',
        logoAlt: 'Balancer',
    },

    modules: {
        balanceSheet: { title: 'Balance Sheet', subtitle: 'Monthly financial overview' },
        budget: { title: 'Budget', subtitle: 'Left to spend this month' },
        ledger: { title: 'Ledger', subtitle: 'Facts you typed this month' },
        statistics: { title: 'Statistics', subtitle: 'Trends and insights' },
        history: { title: 'Past Balance Sheets', subtitle: 'Closed monthly snapshots' },
        standing: { title: 'Standing', subtitle: 'Where you stand overall' },
        settings: { title: 'Settings', subtitle: 'Account preferences' },
        bugReport: { title: 'Report a problem', subtitle: 'Tell us what went wrong' },
    },

    balanceSheet: {
        title: 'Balance Sheet',
        loadingMonth: 'Loading month...',
        refresh: 'Refresh balance sheet',
        loading: 'Loading balance sheet',
        availableCash: 'Available cash',
        savings: 'Savings',
        rollOver: 'Roll over',
        noEntries: 'No entries',
        noEntriesThisMonth: 'No entries this month',
        noChargesThisMonth: 'No charges this month',
        irregular: 'Irregular',
        refunds: 'Refunds',
        showMore: (n: number) => `Show ${n} more`,
        showLess: 'Show less',
        charged: 'Charged',
        projectedRemaining: 'Projected remaining',
        noChargesYet: 'No charges yet this month',
        noRemainingCharges: 'No remaining scheduled charges',
        each: 'each',
        income: 'Income',
        debt: 'Debt',
        purchases: 'Purchases',
        recurring: 'Recurring',
        paid: 'Paid',
        balance: 'Balance',
        remaining: 'Remaining',
        forgiven: 'Forgiven',
        settled: 'Settled',
        thisMonth: 'This month',
        deposit: 'Deposit',
        withdrawal: 'Withdrawal',
        schedules: (n: number) => `${n} schedule${n === 1 ? '' : 's'}`,
        items: (n: number) => `${n} item${n === 1 ? '' : 's'}`,
        chargedCount: (n: number) => `${n} charged`,
        projectedAmount: (amount: string) => ` · ${amount} projected`,
        dayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const,
        annual: 'Annual',
        annualDay: (day: number) => `Annual · day ${day}`,
        weekly: (day: string) => `Weekly · ${day}`,
        monthly: 'Monthly',
        monthlyDay: (day: number) => `Monthly · day ${day}`,
        times: (label: string, n: number) => `${label} × ${n}`,
    },

    budget: {
        title: 'Budget',
        subtitle: 'Measure your spending goals',
        refresh: 'Refresh budget',
        loading: 'Loading budget',
        noPlan: 'No spending plan this month.',
        setPlan: 'Set a monthly spending plan',
        leftToSpend: 'Left to spend',
        overBy: 'Over by',
        ofPlan: (actual: string, plan: string) => `${actual} of ${plan}`,
        monthClosed: 'Month closed',
        dayLeft: '1 day left',
        daysLeft: (n: number) => `${n} days left`,
        purchases: 'Purchases',
        recurring: 'Recurring',
        obligations: 'Obligations',
        noCategoryCaps: 'No category caps.',
        dayToDay: 'Day-to-day',
        everythingElse: 'Everything else',
        postedOfPlanned: (charged: string, plan: string, auto: boolean) => `Posted ${charged} of ${plan} planned${auto ? ' (auto)' : ''}`,
        recurringOver: 'Recurring ran over the plan.',
        left: (amount: string) => `${amount} left`,
        over: (amount: string) => `over ${amount}`,
        ofOriginal: (amount: string) => `of ${amount}`,
        paidThisMonth: (amount: string) => ` · paid ${amount} this month`,
        noOpenDebts: 'No open debts.',
        stillOwed: (amount: string) => `Still owed in total ${amount}`,
        paidThisMonthTotal: (amount: string) => `Paid this month ${amount}`,
        ofPlanned: (amount: string) => ` of ${amount} planned`,
        editPlan: 'Edit plan',
        planLocked: 'Plan locked with the month',
    },

    budgetEdit: {
        title: (month: string) => `Plan for ${month}`,
        description: 'Mark down the spending goals for the month. Unused budget stays in your total available cash.',
        optional: 'optional',
        amountPlaceholder: '0.00',
        purchases: 'Purchases',
        purchasesLabel: 'How much for purchases this month?',
        purchasesHint: 'Food, shopping, extras, etc.',
        alreadySpent: (amount: string) => `You’ve already spent ${amount} on purchases this month.`,
        capsOver: (amount: string) => `Category limits are ${amount} over the purchase total.`,
        leftoverUncapped: (amount: string) => `${amount} of the purchase total has no category limit`,
        splitByCategory: 'Split by category',
        splitHint: 'Optionally split the budget by category to put limits on specific things.',
        hideExtra: 'Hide extra categories',
        chooseFrom: (n: number) => `Choose from ${n} ${n === 1 ? 'category' : 'categories'}`,
        showMoreCategories: (n: number) => `Show ${n} more ${n === 1 ? 'category' : 'categories'}`,
        spentSoFar: (amount: string) => `Spent ${amount} so far this month`,
        nothingSpent: 'Nothing spent in this category yet',
        limitSuffix: (amount: string) => ` · limit ${amount}`,
        setLimit: 'Set a limit',
        close: 'Close',
        limitFor: (name: string) => `Limit for ${name}`,
        recurring: 'Recurring',
        recurringIntro: 'Filled in from your recurring streams.',
        thisMonthsRecurring: 'This month’s recurring',
        noStreams: 'No recurring streams yet — add them in the Ledger and this will fill in.',
        customRecurring: 'Custom recurring total',
        customRecurringHint: 'Overrides the automatic total from streams.',
        backToAuto: 'Back to automatic recurring',
        useDifferentTotal: 'Use a different recurring total',
        debts: 'Debts',
        left: (amount: string) => `${amount} left`,
        ofOriginally: (amount: string) => `of ${amount} originally`,
        paidThisMonth: (amount: string) => ` · paid ${amount} this month`,
        stillOwed: 'Still owed in total',
        noOpenDebts: 'No open debts.',
        debtTarget: 'How much do you want to pay toward these this month?',
        debtHint: '',
        noTarget: 'No target',
        savings: 'Savings',
        saveTarget: 'How much do you want to put aside this month?',
        saveHintLedger: '',
        saveHintSoFar: (amount: string) => `This month so far: ${amount}.`,
        save: 'Save this month’s plan',
        saving: 'Saving…',
        savedToast: 'Plan saved',
        errPurchases: 'Enter how much you want to spend on purchases this month.',
        errCategory: 'Category limits must be a number.',
        errRecurring: 'Enter a recurring total, or switch back to auto.',
        errOptional: 'Optional amounts must be empty or a valid number.',
    },

    statistics: {
        title: 'Statistics',
        subtitle: 'Historical trends, comparisons, and shares',
        refresh: 'Refresh statistics',
        loading: 'Loading statistics',
        timeWindow: 'Time window',
        series: 'Series',
        noData: 'No data in this window.',
        trendNeedsTwo: 'A trend needs at least two months of data.',
        value: 'Value',
        spent: 'Spent',
        plan: 'Plan',
        vsAvg: (delta: string, baseline: string) => `${delta} vs avg ${baseline}`,
        avgPerMonth: (baseline: string) => `avg ${baseline}/mo`,
        views: {
            trend: 'Trend',
            compare: 'Compare',
            share: 'Share',
            markers: 'Markers',
        },
        trendSeries: {
            leftover: 'What’s leftover',
            income_total: 'Income',
            spend_net: 'Purchases',
            recurring_total: 'Recurring charges',
            savings_net: 'Savings',
            savings_running: 'Savings total',
            recurring_load: 'Recurring vs income',
            budget_adherence: 'Budget followed',
            budget_left: 'Budget leftover',
        },
        compareSeries: {
            purchase_categories_month: 'Purchases by category',
            purchase_categories_avg: 'Average by category',
            outflow_domains_month: 'Spending by type',
            leftover_by_month: 'Leftover by month',
            budget_by_category: 'Budget vs spent',
        },
        shareSeries: {
            outflow_mix: 'How money was used',
            purchase_categories: 'Share of purchases',
            income_mix: 'Types of income',
        },
        windows: {
            1: 'This month',
            3: 'Last 3 months',
            6: 'Last 6 months',
            12: 'Last 12 months',
            24: 'Last 2 years',
            60: 'Last 5 years',
            all: 'All time',
        },
    },

    history: {
        title: 'Past Balance Sheets',
        subtitle: 'Closed monthly snapshots',
        refresh: 'Refresh history',
        loading: 'Loading history',
        empty: 'No closed months yet. When you close a month, its snapshot will appear here.',
        income: 'Income',
        spent: 'Spent',
        rollOver: 'Roll over',
        debtPaid: 'Debt paid',
        purchases: 'Purchases',
        recurring: 'Recurring',
        savingsNet: 'Savings (net)',
    },

    standing: {
        title: 'Standing',
        subtitle: 'Cash, savings, and open debt',
        refresh: 'Refresh standing',
        loading: 'Loading standing',
        availableCash: 'Available cash',
        savings: 'Savings',
        stillOwed: 'Still owed',
        trackingSince: (monthLabel: string) => `Since ${monthLabel}`,
        startedThisMonth: 'Started this month',
        monthsTracked: (n: number) => (n === 1 ? '1 month' : `${n} months`),
    },

    ledger: {
        title: 'Ledger',
    },

    settings: {
        drawerTitle: 'Settings',
        drawerDescription: 'Account, money display, and finance tools.',
        sections: {
            account: 'Account',
            money: 'Money display',
            appearance: 'Appearance',
            layout: 'Desktop layout',
            tour: 'Tour',
            local: 'Local only',
            finance: 'Finance',
            security: 'Security',
            session: 'Session',
        },
        firstName: 'First name',
        lastName: 'Last name',
        email: 'Email',
        emailUnverified: 'Email unverified.',
        resendVerification: 'Resend verification',
        verificationSent: 'Verification link sent.',
        save: 'Save',
        saved: 'Saved',
        couldNotUpdate: 'Could not update.',
        couldNotSaveProfile: 'Could not save profile.',
        currency: 'Currency',
        usd: 'USD — US Dollar',
        eur: 'EUR — Euro',
        numberFormat: 'Number format',
        browserDefault: 'Browser default',
        updating: 'Updating…',
        appearance: {
            toggle: 'Toggle theme',
            light: 'Light',
            dark: 'Dark',
            system: 'System',
        },
        layoutBig: 'Big',
        layoutSmall: 'Small',
        layoutHint: '',
        tourHint: 'Rewatch the slideshow if you need a refresher.',
        showTour: 'Show the tour again',
        localHint: 'Temporary. Reset wipes Facts and sends you through onboarding. Load demo rebuilds 24 months and skips the tour.',
        resetOnboarding: 'Reset to onboarding',
        resetConfirm: 'Wipe all financial data and return to onboarding?',
        loadDemo: 'Load demo',
        loadDemoConfirm: 'Replace all financial data with the 24-month demo?',
        lastProcessed: 'Last processed:',
        never: 'Never',
        syncNow: 'Sync now',
        syncSkipped: 'Sync skipped — another process is already running.',
        syncedClosed: (months: string) => `Synced. Closed: ${months}`,
        synced: 'Synced.',
        currentPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm password',
        updatePassword: 'Update password',
        passwordUpdated: 'Password updated',
        couldNotUpdatePassword: 'Could not update password.',
        logOut: 'Log out',
        delete: {
            title: 'Delete account',
            description: 'Delete your account and all of its resources',
            warning: 'Warning',
            caution: 'Please proceed with caution, this cannot be undone.',
            confirmTitle: 'Are you sure you want to delete your account?',
            confirmBody:
                'Once your account is deleted, all of its resources and data will also be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',
            password: 'Password',
            cancel: 'Cancel',
            submit: 'Delete account',
        },
    },

    bugReport: {
        drawerTitle: 'Report a problem',
        drawerDescription: 'Tell us what went wrong.',
        type: 'Type',
        typeAria: 'Issue type',
        typePlaceholder: 'What kind of issue?',
        types: {
            visual: 'Looks wrong',
            functional: "Doesn't work",
            composite: 'Both',
        },
        where: 'Where',
        whereAria: 'Where it happened',
        wherePlaceholder: 'Where did it happen?',
        zones: {
            'balance-sheet': 'Balance Sheet',
            'creator-suite': 'Ledger',
            statistics: 'Statistics',
            budget: 'Budget',
            'past-balance-sheets': 'Past Balance Sheets',
            settings: 'Settings',
            dashboard: 'Dashboard',
            login: 'Login',
            other: 'Other',
        },
        using: 'I was using',
        usingAria: 'Desktop or mobile',
        views: {
            desktop: 'Desktop',
            mobile: 'Mobile',
        },
        whatHappened: 'What happened',
        placeholder: 'What you expected, and what you saw instead.',
        sending: 'Sending…',
        send: 'Send report',
        thanks: 'Thanks — we got it.',
    },
} as const;
