/**
 * User-facing copy for Ledger (creator-suite).
 * Tab keys stay in the components; labels here are what people read.
 */
export const ledgerCopy = {
    tabs: {
        Feed: 'Feed',
        Income: 'Income',
        Purchases: 'Purchases',
        Debts: 'Debts',
        Recurring: 'Recurring',
        Savings: 'Savings',
    },

    common: {
        add: 'Add',
        edit: 'Edit',
        cancel: 'Cancel',
        saveChanges: 'Save Changes',
        saving: 'Saving…',
        saved: 'Saved',
        deleted: 'Deleted',
        archived: 'Archived',
        updated: 'Updated',
        delete: 'Delete',
        archive: 'Archive',
        restore: 'Restore',
        restoring: 'Restoring…',
        loading: 'Loading',
        removing: 'Removing',
        dismissError: 'Dismiss error',
        noRecords: 'No records found.',
        monthLocked: 'This month is locked.',
        checkingLocks: 'Checking month locks…',
        name: 'Name',
        descriptionOptional: 'Description (optional)',
        notesOptional: 'Notes (optional)',
        amount: 'Amount',
        date: 'Date',
        category: 'Category',
        none: 'None',
        uncategorized: 'Uncategorized',
        unlisted: 'Unlisted',
        active: 'Active',
        paused: 'Paused',
        deletePermanent: (name: string) => `Permanently delete "${name}"? This cannot be undone.`,
        skip: 'Skip',
        selectPlaceholder: '— select —',
        noneOption: '— none —',
    },

    filters: {
        search: 'Search name or notes',
        from: 'From date',
        to: 'To date',
        fromShort: 'From',
        toShort: 'To',
        month: 'Month',
        moreFilters: 'More filters',
        fewerFilters: 'Fewer filters',
        domain: 'Domain',
        allTypes: 'All types',
        minAmount: 'Min amount',
        maxAmount: 'Max amount',
        category: 'Category',
        allCategories: 'All categories',
    },

    feed: {
        domain: {
            income: 'Income',
            spending: 'Purchase',
            recurring: 'Recurring',
            debt: 'Debt',
            savings: 'Savings',
        },
        filter: {
            spending: 'Purchases',
            income: 'Income',
            recurring: 'Recurring',
            debt: 'Debts',
            savings: 'Savings',
        },
        empty: 'No facts in this range.',
    },

    income: {
        sub: {
            Schedules: 'Schedules',
            Entries: 'Entries',
            Archive: 'Archive',
        },
        refund: 'Refund',
        regular: 'Regular',
        irregular: 'Irregular',
        entriesHint: 'Add an entry for one-off or irregular income.',
        regularHint: 'This entry was auto-generated from a schedule. You can adjust amount or date in the open month.',
        receivedOn: 'Received on',
        deleteEntry: (name: string, amount: string) => `Delete "${name}" (${amount})?`,
        editEntry: 'Edit Entry',
        newIrregular: 'New Irregular Entry',
        noEntries: 'No income entries yet.',
        noEntriesMatch: 'No entries match these filters.',
        incomeAdded: 'Income added',
        resumePending: 'Resume pending',
        pausePending: 'Pause pending',
        scheduleAdded: 'Schedule added',
        amountUpdated: 'Amount updated',
        pauseSchedule: 'Pause schedule',
        resumeSchedule: 'Resume schedule',
        initialSchedule: 'Initial schedule',
        startsOn: 'Starts on',
        versionHistory: 'Version History',
        updateAmountSchedule: 'Update amount / schedule',
        newVersion: 'New version',
        saveVersion: 'Save version',
        pauseAfterOccurrence: (name: string) => `Pause "${name}" after its next occurrence?`,
        resumeAfterOccurrence: (name: string) => `Resume "${name}" after its next occurrence?`,
        archiveSchedule: (name: string) => `Archive "${name}"? Generated entries remain; no new occurrences will be created.`,
        editSchedule: 'Edit Schedule',
        newSchedule: 'New Schedule',
        noSchedules: 'No regular income schedules yet.',
        dayOfPeriod: (day: number) => `Day ${day} of each period`,
        everyDay: (day: string) => `Every ${day}`,
        noArchivedSchedules: 'No archived schedules.',
        noVersion: 'No version',
    },

    purchases: {
        sub: {
            Items: 'Items',
            Categories: 'Categories',
        },
        refund: 'Refund',
        refundedOf: (refunded: string, total: string) => `Refunded ${refunded} of ${total}`,
        remaining: (amount: string) => `${amount} remaining`,
        payOff: (amount: string) => `Pay off (${amount})`,
        fullRefund: (amount: string) => `Full refund (${amount})`,
        partialRefund: 'Partial refund',
        upToRemaining: (amount: string) => `Up to ${amount} remaining`,
        confirm: 'Confirm',
        back: 'Back',
        confirmFull: (title: string, amount: string) => `Mark "${title}" as fully refunded? This will add a matching income entry of ${amount}.`,
        confirmPayoff: (remaining: string, title: string) => `Refund the remaining ${remaining} for "${title}"? This will fully refund the purchase.`,
        purchaseAdded: 'Purchase added',
        refundRecorded: 'Refund recorded',
        description: 'Description',
        linkOptional: 'Link (optional)',
        linkPlaceholder: 'https://…',
        deletePurchase: (description: string) => `Delete purchase "${description}"? This cannot be undone if the month has already passed.`,
        editPurchase: 'Edit Purchase',
        newPurchase: 'New Purchase',
        noPurchases: 'No purchases yet.',
        noPurchasesMatch: 'No purchases match these filters.',
        refunded: 'Refunded',
        partiallyRefunded: 'Partially Refunded',
        noCategories: 'No purchase categories.',
        deleteCategory: (name: string) =>
            `Remove category "${name}"? It will be unlisted if purchases reference it but will still appear in historical reports.`,
    },

    debts: {
        sub: {
            Debts: 'Debts',
            Payments: 'Payments',
            Categories: 'Categories',
        },
        debtAdded: 'Debt added',
        forgivenToast: 'Forgiven',
        forgiven: 'Forgiven',
        settled: 'Settled',
        description: 'Description',
        categoryOptional: 'Category (optional)',
        totalAmount: 'Total Amount',
        issueDate: 'Issue Date',
        archiveDebt: (name: string) => `Archive "${name}"? It stays on past balance sheets but will not be included in future reports.`,
        forgiveDebt: (name: string) => `Mark "${name}" as forgiven? Remaining balance will be written off.`,
        editDebt: 'Edit Debt',
        newDebt: 'New Debt',
        noDebts: 'No debts yet.',
        forgive: 'Forgive',
        paymentAdded: 'Payment added',
        paidAt: 'Paid At',
        deletePayment: (amount: string) => `Delete payment of ${amount}?`,
        editPayment: 'Edit Payment',
        newPayment: 'New Payment',
        noPayments: 'No payments for this debt.',
        noPaymentsMatch: 'No payments match these filters.',
        debt: 'Debt',
        selectDebt: '— select a debt —',
        remainingLeft: (amount: string) => `${amount} left`,
        balance: (remaining: string, total: string) => `Balance: ${remaining} / ${total}`,
        closedNoPayments: (status: string) => `This debt is ${status} — no new payments.`,
        forgivenLower: 'forgiven',
        settledLower: 'settled',
        noCategories: 'No debt categories.',
        deleteCategory: (name: string) => `Delete debt category "${name}"?`,
    },

    recurring: {
        sub: {
            Streams: 'Streams',
            Charges: 'Charges',
            Categories: 'Categories',
            Archive: 'Archive',
        },
        selectCategory: '— select category —',
        fallbackCategory: (id: number) => `Category ${id}`,
        chargesHint: 'Select a stream to adjust the amount in an open month, or delete to skip that occurrence.',
        chargeHint: 'You can adjust the amount in the open month. Deleting skips this occurrence so it is not generated again.',
        stream: 'Stream',
        chargedOn: 'Charged on',
        skipConfirm: (name: string, date: string, amount: string) =>
            `Skip "${name}" on ${date} (${amount})? This occurrence will not be generated again.`,
        charge: 'Charge',
        charges: 'Charges',
        noCharges: 'No recurring charges yet.',
        noChargesMatch: 'No charges match these filters.',
        occurrenceSkipped: 'Occurrence skipped',
        resumePending: 'Resume pending',
        pausePending: 'Pause pending',
        streamAdded: 'Stream added',
        priceUpdated: 'Price updated',
        pauseStream: 'Pause stream',
        resumeStream: 'Resume stream',
        cancelQueued: 'Click to cancel queued change',
        takesEffect: 'Takes effect after next charge date',
        noPrice: 'No price set yet. Add one below.',
        dayOfEach: (day: number, unit: string) => `Day ${day} of each ${unit}`,
        year: 'year',
        month: 'month',
        everyShortDay: (day: string) => `Every ${day}`,
        shortDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const,
        updatePrice: '+ Update subscription price',
        updatePriceTitle: 'Update Price',
        newAmount: 'New Amount',
        effectiveFrom: 'Effective From',
        applyPrice: 'Apply Price Change',
        priceHistory: 'Price History',
        archiveStream: (name: string) => `Archive "${name}"? You can restore it later from the Archive tab.`,
        pauseAfterCharge: (name: string) => `Pause "${name}" after its next charge? It stays on the balance sheet until then.`,
        resumeAfterCharge: (name: string) => `Resume "${name}" after its next charge?`,
        pauseAfterNext: 'Pause after next charge',
        resumeAfterNext: 'Resume after next charge',
        editStream: 'Edit Stream',
        newStream: 'New Stream',
        noStreams: 'No recurring streams yet.',
        noCategories: 'No recurring categories.',
        noArchivedStreams: 'No archived streams.',
    },

    savings: {
        withdrawalAdded: 'Withdrawal added',
        depositAdded: 'Deposit added',
        type: 'Type',
        month: 'Month (YYYY-MM)',
        deleteTxn: (type: string, amount: string) => `Delete this ${type} of ${amount}?`,
        editTxn: 'Edit Transaction',
        newTxn: 'New Transaction',
        noTxns: 'No savings transactions yet.',
        noTxnsMatch: 'No transactions match these filters.',
        deposit: 'Deposit',
        withdrawal: 'Withdrawal',
        noNotes: 'No notes',
        total: 'Total:',
    },

    categories: {
        added: 'Category added',
        remove: (name: string) => `Remove category "${name}"?`,
        edit: 'Edit Category',
        new: 'New Category',
    },

    archive: {
        restored: 'Restored',
        permanentlyDeleted: 'Permanently deleted',
        deletePermanent: (name: string) => `Permanently delete "${name}"? This cannot be undone.`,
        deletePermanently: 'Delete permanently',
    },

    schedule: {
        incomeFreq: {
            weekly: 'Weekly',
            biweekly: 'Biweekly',
            monthly: 'Monthly',
            bimonthly: 'Every 2 months',
            quarterly: 'Quarterly',
            trimester: 'Trimester',
            biannually: 'Biannually',
            annual: 'Annually',
        },
        dayNames: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as const,
        yearly: 'Yearly',
        weekly: 'Weekly',
        monthly: 'Monthly',
        on: 'On',
        off: 'Off',
        amount: 'Amount',
        effectiveFrom: 'Effective from',
        startsOn: 'Starts on',
        frequency: 'Frequency',
        dayOfWeek: 'Day of week',
        dayOfMonth: 'Day of month',
        anchorDate: 'Anchor date',
        hide: '▲ Hide',
        show: '▼ Show',
        now: ' → now',
        current: 'current',
    },
} as const;
